// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AgentArcadeClientProgram;

impl AgentArcadeClientProgram {
    pub const ROUTE_ID_AGENT_ARCADE: u8 = 1;
}

impl sails_rs::client::Program for AgentArcadeClientProgram {}

pub trait AgentArcadeClient {
    type Env: sails_rs::client::GearEnv;
    fn agent_arcade(&self) -> sails_rs::client::Service<agent_arcade::AgentArcadeImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> AgentArcadeClient
    for sails_rs::client::Actor<AgentArcadeClientProgram, E>
{
    type Env = E;
    fn agent_arcade(&self) -> sails_rs::client::Service<agent_arcade::AgentArcadeImpl, Self::Env> {
        self.service(AgentArcadeClientProgram::ROUTE_ID_AGENT_ARCADE)
    }
}
pub trait AgentArcadeClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AgentArcadeClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> AgentArcadeClientCtors
    for sails_rs::client::Deployment<AgentArcadeClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AgentArcadeClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> (), 0);
}

pub mod agent_arcade {
    use super::*;

    #[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo, ReflectHash)]
    #[codec(crate = sails_rs::scale_codec)]
    #[type_info(crate = sails_rs::type_info)]
    #[reflect_hash(crate = sails_rs)]
    pub enum ArcadeError {
        InvalidScore,
        InvalidStats,
        LimitTooLarge,
    }
    #[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo, ReflectHash)]
    #[codec(crate = sails_rs::scale_codec)]
    #[type_info(crate = sails_rs::type_info)]
    #[reflect_hash(crate = sails_rs)]
    pub struct LeaderboardEntry {
        pub rank: u32,
        pub player: ActorId,
        pub best_score: u32,
        pub tasks_completed: u32,
        pub threats_dodged: u32,
        pub run_id: u64,
        pub updated_at: u64,
    }
    #[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo, ReflectHash)]
    #[codec(crate = sails_rs::scale_codec)]
    #[type_info(crate = sails_rs::type_info)]
    #[reflect_hash(crate = sails_rs)]
    pub struct PlayerScore {
        pub player: ActorId,
        pub best_score: u32,
        pub tasks_completed: u32,
        pub threats_dodged: u32,
        pub run_id: u64,
        pub updated_at: u64,
    }
    #[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo, ReflectHash)]
    #[codec(crate = sails_rs::scale_codec)]
    #[type_info(crate = sails_rs::type_info)]
    #[reflect_hash(crate = sails_rs)]
    pub struct SubmitScoreReply {
        pub run_id: u64,
        pub accepted: bool,
        pub improved: bool,
        pub previous_best: u32,
        pub current_best: u32,
        pub rank: Option<u32>,
    }

    pub trait AgentArcade {
        type Env: sails_rs::client::GearEnv;
        fn game_info(&self) -> sails_rs::client::PendingCall<io::GameInfo, Self::Env>;
        fn leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env>;
        fn player_best_score(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestScore, Self::Env>;
        fn player_rank(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerRank, Self::Env>;
        fn scores_count(&self) -> sails_rs::client::PendingCall<io::ScoresCount, Self::Env>;
        fn submit_score(
            &mut self,
            score: u32,
            tasks_completed: u32,
            threats_dodged: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitScore, Self::Env>;
    }

    pub struct AgentArcadeImpl;

    impl sails_rs::client::Identifiable for AgentArcadeImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([68, 245, 202, 68, 1, 55, 135, 86]);
    }

    impl<E: sails_rs::client::GearEnv> AgentArcade for sails_rs::client::Service<AgentArcadeImpl, E> {
        type Env = E;
        fn game_info(&self) -> sails_rs::client::PendingCall<io::GameInfo, Self::Env> {
            self.pending_call(())
        }
        fn leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env> {
            self.pending_call((limit,))
        }
        fn player_best_score(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestScore, Self::Env> {
            self.pending_call((player,))
        }
        fn player_rank(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerRank, Self::Env> {
            self.pending_call((player,))
        }
        fn scores_count(&self) -> sails_rs::client::PendingCall<io::ScoresCount, Self::Env> {
            self.pending_call(())
        }
        fn submit_score(
            &mut self,
            score: u32,
            tasks_completed: u32,
            threats_dodged: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitScore, Self::Env> {
            self.pending_call((score, tasks_completed, threats_dodged))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(GameInfo () -> String, 0, <super::AgentArcadeImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Leaderboard (limit: u32) -> Vec<super::LeaderboardEntry> | super::ArcadeError, 1, <super::AgentArcadeImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PlayerBestScore (player: ActorId) -> super::Option<super::PlayerScore, >, 2, <super::AgentArcadeImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PlayerRank (player: ActorId) -> super::Option<u32, >, 3, <super::AgentArcadeImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ScoresCount () -> u32, 4, <super::AgentArcadeImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SubmitScore (score: u32, tasks_completed: u32, threats_dodged: u32) -> super::SubmitScoreReply | super::ArcadeError, 5, <super::AgentArcadeImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode, ReflectHash)]
        #[codec(crate = sails_rs::scale_codec)]
        #[reflect_hash(crate = sails_rs)]
        pub enum AgentArcadeEvents {
            #[codec(index = 0)]
            BestScoreUpdated {
                player: ActorId,
                run_id: u64,
                previous_best: u32,
                new_best: u32,
                tasks_completed: u32,
                threats_dodged: u32,
                updated_at: u64,
            },
        }

        impl AgentArcadeEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::BestScoreUpdated { .. } => 0,
                }
            }
        }

        impl sails_rs::client::Event for AgentArcadeEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for AgentArcadeEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <AgentArcadeImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for AgentArcadeImpl {
            type Event = AgentArcadeEvents;
        }
    }
}
